from qiskit import QuantumRegister, ClassicalRegister, QuantumCircuit
from numpy import pi

qreg_q = QuantumRegister(8, 'q')
creg_c = ClassicalRegister(2, 'c')
circuit = QuantumCircuit(qreg_q, creg_c)

circuit.h(qreg_q[0])
circuit.h(qreg_q[1])
circuit.x(qreg_q[7])
circuit.h(qreg_q[7])
circuit.x(qreg_q[0])
circuit.x(qreg_q[1])
circuit.x(qreg_q[2])
circuit.ccx(qreg_q[0], qreg_q[1], qreg_q[2])
circuit.x(qreg_q[0])
circuit.x(qreg_q[1])
circuit.x(qreg_q[1])
circuit.x(qreg_q[3])
circuit.ccx(qreg_q[0], qreg_q[1], qreg_q[3])
circuit.x(qreg_q[1])
circuit.x(qreg_q[0])
circuit.x(qreg_q[4])
circuit.ccx(qreg_q[1], qreg_q[0], qreg_q[4])
circuit.x(qreg_q[0])
circuit.ccx(qreg_q[3], qreg_q[2], qreg_q[5])
circuit.ccx(qreg_q[5], qreg_q[4], qreg_q[6])
circuit.cx(qreg_q[6], qreg_q[7])
circuit.ccx(qreg_q[4], qreg_q[5], qreg_q[6])
circuit.ccx(qreg_q[2], qreg_q[3], qreg_q[5])
circuit.x(qreg_q[0])
circuit.x(qreg_q[4])
circuit.ccx(qreg_q[0], qreg_q[1], qreg_q[4])
circuit.x(qreg_q[0])
circuit.x(qreg_q[1])
circuit.x(qreg_q[3])
circuit.ccx(qreg_q[0], qreg_q[1], qreg_q[3])
circuit.x(qreg_q[1])
circuit.x(qreg_q[0])
circuit.x(qreg_q[1])
circuit.x(qreg_q[2])
circuit.ccx(qreg_q[0], qreg_q[1], qreg_q[2])
circuit.x(qreg_q[0])
circuit.x(qreg_q[1])
circuit.h(qreg_q[0])
circuit.h(qreg_q[1])
circuit.x(qreg_q[0])
circuit.x(qreg_q[1])
circuit.cz(qreg_q[0], qreg_q[1])
circuit.x(qreg_q[0])
circuit.x(qreg_q[1])
circuit.h(qreg_q[0])
circuit.h(qreg_q[1])
circuit.measure(qreg_q[0], creg_c[0])
circuit.measure(qreg_q[1], creg_c[1])